apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crashi
  name: crashi
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: crashi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crashi
    spec:
      containers:
      - command:
        - uvicorn
        - app:app
        - --host=0.0.0.0
        - --port=5005
        env:
        - name: CRASH_SCHEDULE
          value: "* * * * *"
        - name: SIM_ENV_MISSING
          value: "NO"
        - name: SIM_HIDDEN_ENV_MISSING
          value: "YES"
        image: ghcr.io/jon-funk/crashi:latest
        imagePullPolicy: Always
        name: crashi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: cache-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache-volume