name: Build And Push

on:
  push:
    branches:    
      - main

env:
  IMAGE: crashi
  TAG: latest
  DOCKERFILE: dockerfile
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -f ${{ env.DOCKERFILE }} -t ${{ env.IMAGE }}:${{ env.TAG }} .
      - name: Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
          docker push ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}